apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  namespace: default
spec:
  # Use ClusterIP for internal access, or LoadBalancer/NodePort for external access
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  # This selector links the Service to the Deployment Pods
  selector:
    app: my-web-app
